# Generated by Django 4.1.6 on 2023-05-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('blood_type', models.CharField(max_length=10)),
                ('town', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=20)),
                ('photo_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
