# Generated by Django 4.1.6 on 2023-05-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodBank', '0001_initial'),
        ('Donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='blood_banks',
            field=models.ManyToManyField(related_name='donors', to='BloodBank.bloodbank'),
        ),
    ]
